services:
  django-app:
    build:
      context: .
    command: sh -c "python3 manage.py collectstatic --noinput && gunicorn -c gunicorn_config.py listhias.wsgi:application"
    container_name: listhias
    expose:
      - "8000"
    env_file:
     - .env
    volumes:
      - .:/django-app
      - ./staticfiles/:/app/staticfiles/
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      CLIENT_ID_ANIMELIST: ${CLIENT_ID_ANIMELIST}
      CLIENT_SECRET_ANIMELIST: ${CLIENT_SECRET_ANIMELIST}
      CLIENT_ID_MOVIE_DB: ${CLIENT_ID_MOVIE_DB}
      DEBUG: ${DEBUG}

  nginx:
      image: nginx:alpine
      container_name: nginx
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./nginx/conf.d/:/etc/nginx/conf.d/
        - ./staticfiles/:/app/staticfiles/
      depends_on:
        - django-app

  # dns: