services:
  web:
    build:
      context: ./django/
    command: gunicorn -c gunicorn_config.py listhias.wsgi:application
    env_file:
     - .env
    volumes:
      - ./django:/usr/src/app/
      - ./django/staticfiles/:/usr/src/app/staticfiles/
    expose:
      - 8000
    environment:
      DEBUG: ${DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      CLIENT_ID_ANIMELIST: ${CLIENT_ID_ANIMELIST}
      CLIENT_SECRET_ANIMELIST: ${CLIENT_SECRET_ANIMELIST}
      CLIENT_ID_MOVIE_DB: ${CLIENT_ID_MOVIE_DB}
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/mysql/db:/var/lib/mysql

  nginx:
    build:
      context: ./nginx/
    volumes:
      - ./django/staticfiles/:/home/app/staticfiles/
    ports:
      - 80:80
    depends_on:
      - web
