# Generated by Django 5.1.4 on 2025-01-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_user_description_item_user_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='additional_info',
            field=models.JSONField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('todo_list', 'Todo List'), ('movie', 'Movie'), ('tv_show', 'TV Show'), ('anime', 'Anime')], max_length=10),
        ),
    ]
