# Generated by Django 5.1.4 on 2025-01-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_item_additional_info_alter_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='additional_info',
            field=models.JSONField(null=True),
        ),
    ]
